### ISSUE TITLE
数据无法下载

### ISSUE THREAD

**Issue by AISTUDYML** [meng-wenlong/LMSanitator#1]
<img width="628" alt="屏幕截图 2024-10-22 172923" src="https://github.com/user-attachments/assets/b7de17cf-eca3-421b-8ce4-f12bd0359c0e">
数据无法下载，进入图中网页链接，也并没有相关数据下载。这该怎么解决呀
<img width="644" alt="屏幕截图 " src="https://github.com/user-attachments/assets/75ce4d75-cc4d-471d-a275-39d4d066a33d">

**Comment by meng-wenlong** [comment]
In which line you encounted this error?

**Comment by AISTUDYML** [comment]
您好，我是在运行这一个命令的时候
python insert_backdoor.py --model_type roberta --model_name_or_path roberta-base
出现了错误

我想打开网页链接，下载到本地，但也未能成功。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meng-wenlong/LMSanitator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月22日(星期二) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meng-wenlong/LMSanitator] 数据无法下载 (Issue #1)





 
In which line you encounted this error?

**Comment by meng-wenlong** [comment]
Can you provide the whole error messages?

**Comment by AISTUDYML** [comment]
您好，请问能看到我邮件里的图片吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meng-wenlong/LMSanitator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月22日(星期二) 晚上6:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meng-wenlong/LMSanitator] 数据无法下载 (Issue #1)





 
Can you provide the whole error messages?

**Comment by AISTUDYML** [comment]
您好，我是在运行这一个命令
python insert_backdoor.py --model_type roberta --model_name_or_path roberta-base
出现了错误

完整的错误信息如下
<img width="770" alt="屏" src="https://github.com/user-attachments/assets/ce8d8d81-cebc-491e-8be5-8aadada95e3d">

**Comment by AISTUDYML** [comment]
当我尝试打开给出的网页链接，想将数据下载到本地时，打开网页之后并给出我想要的数据
![Uploading 屏幕截图 .png…]()

**Comment by AISTUDYML** [comment]
当我尝试打开给出的网页链接，想将数据下载到本地时，打开网页之后并给出我想要的数据
![Uploading 屏幕截图 2024-10-22 185748.png…]()

**Comment by meng-wenlong** [comment]
Thanks for your report! I guess it is because `datasets` package is too old. `pip install --upgrade datasets` solves my problem.

**Comment by AISTUDYML** [comment]
很抱歉再次打扰，我按您的要求继续操作之后，出现报错需要分配GPU，当我分配之后，出现了一个新的我不知道该如何解决的问题
<img width="512" alt="屏幕截图 2024-10-22 200144" src="https://github.com/user-attachments/assets/d37bb903-bda9-406f-a878-70d8a98d1b4b">
<img width="512" alt="屏幕截图 2024-10-22 200208" src="https://github.com/user-attachments/assets/c3b3a6d3-2c78-41e7-a018-df11bd198bbc">

**Comment by meng-wenlong** [comment]
It seems that your machine has no Nvidia GPU equipted. You can use `import torch; print(torch.cuda.is_available())` to check whether your GPUs are correctly set.

**Comment by AISTUDYML** [comment]
是的，但是随后我从服务器中申请了一块GPU来运行该命令，然后报错了，完整的错误信息就在上面回复消息的第二张图片里。

**Comment by meng-wenlong** [comment]
I cannot reproduce the error. Maybe you can rm /home/mengyan24/.cache/huggingface/datasets/downloads/ and retry

**Comment by AISTUDYML** [comment]
好的好的，谢谢

**Comment by AISTUDYML** [comment]
很抱歉，今天我又重新去下载数据还是出现问题，请问可以直接发数据包给我吗？

**Comment by AISTUDYML** [comment]
我想本地下载，但似乎进入 https://s3.amazonaws.com/research.metamind.io/wikitext/wikitext-103-v1.zip，我并没有权限
<img width="458" alt="屏幕截图 2024-10-27 135219" src="https://github.com/user-attachments/assets/063230a7-0988-4c9c-8beb-1072dac24c89">

**Comment by meng-wenlong** [comment]
You can download it from HuggingFace: https://huggingface.co/datasets/Salesforce/wikitext

**Comment by AISTUDYML** [comment]
好的好的，谢谢！
